### ISSUE TITLE
pr: testing failing on AWS LimitExceeded

### ISSUE THREAD

**Issue by yossig-aquasec** [redhat-openshift-ecosystem/community-operators-prod#1021]
example:
pr: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1020
example failure: 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/1020/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.6-deploy-operator-on-openshift/1508735887767244800

level=error msg="Error: Error creating IAM instance profile ci-op-42r2swbg-96ace-47qjt-bootstrap-profile: LimitExceeded: Cannot exceed quota for InstanceProfilesPerAccount: 1000"
level=error msg="\tstatus code: 409, request id: a5f9b283-4ba6-4c0c-852f-750e014db50d"

**Comment by yossig-aquasec** [comment]
also this:
level=error
level=error msg=Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
level=error msg=	status code: 400, request id: b1ebd38f-267b-4dd4-bef2-642676484609
level=error
level=error msg=  on ../tmp/openshift-install-cluster-663863207/vpc/vpc.tf line 6, in resource "aws_vpc" "new_vpc":
level=error msg=   6: resource "aws_vpc" "new_vpc" {

**Comment by J0zi** [comment]
@yossig-aquasec  This is under responsibility of AWS CI admins. We rely on DPTP service running on AWS. They were facing issues.
