### ISSUE TITLE
Flakey test: Operator test / kiwi / Full operator test :  The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'latest'

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#1032]
Flakey test? The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'latest'

This test  passed previously with exactly the same code, so I assume it's a bug in the test:
 * https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/workflows/operator_test.yaml?query=branch%3Acert-manager-1.7.2++ 

[Operator test / kiwi / Full operator test (pull_request_target) Failing after 3m — kiwi / Full operator test](https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/5739913337?check_suite_focus=true) 
```
TASK [operator_index : Set versions and versions_bt] ***************************
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'latest'
  
    The error appears to be in '/playbooks/upstream/roles/operator_index/tasks/op_index.yml': line 75, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: "Set versions and versions_bt"
      ^ here

PLAY RECAP *********************************************************************
localhost                  : ok=186  changed=47   unreachable=0    failed=1    skipped=190  rescued=0    ignored=0   
```

_Originally posted by @wallrj in https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/1023#issuecomment-1082798192_

**Comment by J0zi** [comment]
fixed
