### ISSUE TITLE
Error in pushing ibm-block-csi-operator-community (1.9.0) 

### ISSUE THREAD

**Issue by matancarmeli7** [redhat-openshift-ecosystem/community-operators-prod#1050]
We [pushed](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/949) a new version of our product and I see now that the actions after the push were failed on a syntax error of Ansible code, can you help me with that? make sure that the CI on this commit will pass? this error can cause problems? 
the GitHub actions run is:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/5630214925?check_suite_focus=true

thanks

**Comment by J0zi** [comment]
@matancarmeli7 your operator was merged and published correctly. You can ignore this error for now. We are going to improve status handling.

**Comment by J0zi** [comment]
Feel free to reopen if there is some issue.
