### ISSUE TITLE
OCP 4.7 community-operators missing external-secrets-operator v0.5.1

### ISSUE THREAD

**Issue by slopezz** [redhat-openshift-ecosystem/community-operators-prod#1066]
We are using different OCP versions (4.7, 4.8, 4.9), and since https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1060 was merged, **external-secrets-operator** have upgraded to `v0.5.1` on OCP 4.8 and OCP 4.9, but clusters with OCP 4.7 have their latest version stuck at `v0.5.0`.

We tried recreating community-operator catalog pod without success.

Could you please submit **external-secrets-operator** `v0.5.1` to OCP 4.7 community-operator catalog?

Thanks in advance

**Comment by J0zi** [comment]
@slopezz please check again

**Comment by slopezz** [comment]
> @slopezz please check again

It is working @J0zi, thank you!
