### ISSUE TITLE
bundles wasn't published after merging

### ISSUE THREAD

**Issue by yossig-aquasec** [redhat-openshift-ecosystem/community-operators-prod#1191]
Hi, we migrated our operator to bundle format and added 2 new versions , but our bundle didn't publish although the pr was merged
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1181
https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/2305720902

**Comment by yossig-aquasec** [comment]
sorry now the bundles are showing, but after we moved to bundle format we can't  add component from the ui
create instance are gone, did we missed something with the migration?
![image](https://user-images.githubusercontent.com/82142290/168015696-948e2d32-0554-4773-8102-5596277033ea.png)

comparing to previous:

![image](https://user-images.githubusercontent.com/82142290/168015893-91cec1b9-888e-4735-b7b2-c88bedb35bb4.png)

**Comment by mvalarh** [comment]
It is fixed now. Please reopen when needed
