### ISSUE TITLE
Release 5.1.0: community-windows-machine-config-operator - Can't pull image

### ISSUE THREAD

**Issue by Weniga** [redhat-openshift-ecosystem/community-operators-prod#1296]
The image can not be pulled. In the file `community-windows-machine-config-operator.5.1.0.clusterserviceversion.yaml `only the image tag is given, but not the complete path.

Line 279: `image: community-4.10-43fec34`

Should be: `quay.io/openshift-windows/community-windows-machine-config-operator:image: community-4.10-43fec34`

**Comment by J0zi** [comment]
looking into it

**Comment by J0zi** [comment]
this will fix it https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1279

**Comment by alinaryan** [comment]
@Weniga this is now fixed in #1279

**Comment by J0zi** [comment]
closing, feel free to reopen if needed
