### ISSUE TITLE
Github workflow step should verify the status of community signing pipeline trigger 

### ISSUE THREAD

**Issue by wcheang** [redhat-openshift-ecosystem/community-operators-prod#1413]
(Please let me know if a Jira is preferred and which project to file it)
Currently, the community signing pipeline is triggered by a curl command within the github workflow, but the results are not verified. If the webhook fails or malfunctions, new community-operator-index images would be left unsigned and become unpullable, without anyone knowing. The "Sign index" workflow step should check the return code of the webhook query, and fail the step if a non-2xx code is returned. Optionally, it'll be good if the step can then retry the query a few times until it succeeds.

**Comment by J0zi** [comment]
@wcheang thank you for pointing that out, please open a ticket.

**Comment by wcheang** [comment]
This has been moved to jira and implemented: https://issues.redhat.com/browse/CVP-3130
