### ISSUE TITLE
Text hint in CI output contains incorrect operator name

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#1800]
@J0zi Here's an issue to track the incorrect operator name issue that you identified.

> there is no `openebs` operator involved. It is just text hint, which should contain variable with the name of your operator. I will fix it.

_Originally posted by @J0zi in https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/1777#issuecomment-1293440913_

**Comment by J0zi** [comment]
fixed
