### ISSUE TITLE
CI artifacts should include deployment conditions

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#1801]
The CI artifacts include a description of all the Deployment resources for the operator-under-test, 
but the description does not include the `Deployment.Status.Conditions` which contains   error messagez linked to the  Replicaset resources of the Deployment, because the output is generated using `oc describe`.

The artifact should be generated using `og get deployment -o yaml` instead, which includes the full Deployment Status.

>> Literally it is failing to create the first replica in the namespace. So no logs from non existing pod. `ReplicaFailure True FailedCreate`

> Sure. But I was looking for a log of all the Kubernetes Events.
> Or something else to say *why* it failed to create the Pod.

_Originally posted by @wallrj in https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/1777#issuecomment-1293476077_

**Comment by J0zi** [comment]
Good idea.
