### ISSUE TITLE
Aqua Community Operator PR is failing

### ISSUE THREAD

**Issue by BaruchBilanski** [redhat-openshift-ecosystem/community-operators-prod#1899]
Hi, my PR is failing on 4.11 ,4.8 with the following errors:

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/1887/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.11-deploy-operator-on-openshift/1597881082429050880

My PR:
[Link](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1914)

**Comment by BaruchBilanski** [comment]
any news? couldn't understand why it fails on the 4.11

**Comment by BaruchBilanski** [comment]
any update?

**Comment by J0zi** [comment]
That's our bug. Once fixed, it will be merged automatically.
