### ISSUE TITLE
Remove the 'olm.maxOpenShiftVersion' from etcd operator

### ISSUE THREAD

**Issue by dirgim** [redhat-openshift-ecosystem/community-operators-prod#193]
### Initial issue:
Hi, I checked the etcd operator, and found it was added the `olm.maxOpenShiftVersion=4.8`, 

[cloud-user@preserve-olm-env jian]$ oc get csv etcdoperator.v0.9.4  -o yaml|grep "maxOpenShiftVersion"
    olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]'

But, I have changed its `apiextensions.k8s.io` to v1 from v1beta, see: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/127 

So, can we remove the 'olm.maxOpenShiftVersion' from it? Thanks! 

Based on my understanding, the operators which use the  deprecated API should be added the `olm.maxOpenShiftVersion=4.8`, not all of them. Correct me if I'm wrong, thanks!

### Initial answer
If you have fixed API, you can definitely remove 'olm.maxOpenShiftVersion', fully agree.

### Follow up question:
Hi , sorry, I'm confused. How can I fix it on my side? Thanks! I guess this 'olm.maxOpenShiftVersion' property is added when creating the bundle in your script or code

**Comment by camilamacedo86** [comment]
Hi @dirgim, 

The max ocp versions should be set only in the cases that are not compatible with 4.9+.
Do you change previous scenarios? Did you make these specific versions that you want to remove the max OCP version compatible with 4.9+?
