### ISSUE TITLE
Unexpected behaviour when `/retest` is used

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#2059]
After https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2056#issuecomment-1380264014 I commented with `/retest` which triggered a bot to comment `/hold` then `/hold cancel` which re-ran the failed tests, but:

1. The `hold` label did not get removed
2. When I commented `/hold cancel` it triggered *all* the tests to run again.

**Comment by mvalarh** [comment]
Yes, you are right, maybe we should do some timeout before trigger /hold cancel

**Comment by mvalarh** [comment]
This is fixed in current pipline. I added timeout of 10 sec, between comments. Reopen when needed
