### ISSUE TITLE
Error failed to generate steps from config: failed to resolve release latest: failed to request latest release: server responded with 404: no tags exist within the release that satisfy the request

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#2067]
I encountered this error in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2066 but I don't know if it's an error in my OLM bundle or an error in the CI scripts.
 

> 
> INFO[2023-01-13T10:50:22Z] ci-operator version v20230113-3c323d4be      
> INFO[2023-01-13T10:50:22Z] Loading configuration from https://config.ci.openshift.org/ for redhat-openshift-ecosystem/community-operators-prod@main [4.12] 
> INFO[2023-01-13T10:50:22Z] Resolved source https://github.com/redhat-openshift-ecosystem/community-operators-prod to main@2bf1513c, merging: #2066 35b5a822 @wallrj 
> INFO[2023-01-13T10:50:22Z] Requesting a release from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4.12.0-0.nightly/latest?rel=1 
> INFO[2023-01-13T10:50:22Z] Ran for 0s                                   
> ERRO[2023-01-13T10:50:22Z] Some steps failed:                           
> ERRO[2023-01-13T10:50:22Z] 
>   * failed to generate steps from config: failed to resolve release latest: failed to request latest release: server responded with 404: no tags exist within the release that satisfy the request 
> INFO[2023-01-13T10:50:22Z] Reporting job state 'failed' with reason 'defaulting_config:resolving_release'

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/2066/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.12-deploy-operator-on-openshift/1613850907231916032

**Comment by wallrj** [comment]
Another example of this error from https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2018#issuecomment-1381376470

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-openshift-ecosystem_community-operators-prod/2018/pull-ci-redhat-openshift-ecosystem-community-operators-prod-main-4.12-deploy-operator-on-openshift/1613786448954134528

**Comment by wallrj** [comment]
@J0zi  @mvalarh Please take a look at this. It's preventing me releasing cert-manager 1.10.2

**Comment by J0zi** [comment]
This is a temporary Prow job issue, out of our scope.

**Comment by wallrj** [comment]
@jozzi This error is still occurring. Can you post a  link to an issue describing the root problem? I suggest re-opening this for the benefit of other OperatorHub packagers who are also blocked by this. E.g.

 * https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2076#issuecomment-1385276400
 * https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2073#issuecomment-1384643908
