### ISSUE TITLE
Is there a reason the prometheus operator is limited to Single Namespace and OwnNamespace mode?

### ISSUE THREAD

**Issue by etsauer** [redhat-openshift-ecosystem/community-operators-prod#210]
Hey All,

Just wondering if there was any history here or if people would be open to  enabling Multi-namespace and AllNamespace capabilities, which makes this operator far more powerful/capable. I've used the underlying operator enough to know that its fully capable of being used in this way, just wondering if there was concern about conflicts with the openshift-monitoring infrastructure, or some other reason this isn't allowed.

**Comment by camilamacedo86** [comment]
Hi @etsauer, 

That is something that you will need to check with the maintainers of this operator. The issue here in this repo is regard their distribution on the OCP/OLM catalogue only. 

Could you please raise an issue for its maintainers in their repo?

**Comment by etsauer** [comment]
@camilamacedo86 looking at the repo history, the contributor who added the prometheus operator to OH was @J0zi , who does not appear to be a contributor to the operator rep itself. That is why I chose to open the issue here.

https://github.com/prometheus-operator/prometheus-operator/graphs/contributors

**Comment by etsauer** [comment]
@camilamacedo86  I got the same response on the proemtheus-operator so, I need some advice.

I'd love to just submit the change myself, but I'm struggling with this issue: https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/237

**Comment by camilamacedo86** [comment]
Hi @etsauer,

Could we not close this one? is not it fixed in https://github.com/prometheus-operator/prometheus-operator/issues/4265? 
 
Regards #237 it not supporting podman so far but you can use docker right?
