### ISSUE TITLE
AWX not returning newer versions as of 4.13

### ISSUE THREAD

**Issue by omenos** [redhat-openshift-ecosystem/community-operators-prod#2729]
I'm running two instances of OKD that I upgraded from 4.12 to 4.13 yesterday. Both clusters were running a copy of the AWX operator installed via the platform's OperatorHub console (`v2.0.0` and `v2.2.1` respectively). After upgrading to 4.13, OperatorHub only reports `v0.30.0` as available, which I'm guessing is due to the `metadata/annotations.yaml` files for AWX containing the following content, except for `v0.30.0` which lacks it completely:

```yaml
annotations:
  com.redhat.openshift.versions: v4.10-v4.12
```

I can submit a PR that either adds the line to `v0.30.0` and updates it to `v4.{10,11}-v4.13` (whichever is preferred) for all files, or just removes the annotation from all variants.

**Comment by mporrato** [comment]
@john-westcott-iv @rooftopcellist FYI

**Comment by rooftopcellist** [comment]
@omenos A PR here that adds the v4.13 annotation to awx-operator v2.2.1 would be welcome.  

@john-westcott-iv and I have updated our automation so that Openshift v4.13 will be part of the annotation range in future awx-operator releases.

**Comment by omenos** [comment]
@rooftopcellist Do you want me to modify any other versions or just 2.2.1? And should 0.30.0 be left without that annotation?

**Comment by omenos** [comment]
This issue is fixed as of the release of AWX Operator 2.3.0 (no older version available).
