### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by jmazzitelli** [redhat-openshift-ecosystem/community-operators-prod#2753]
see: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2747

The CI tests are failing that do not look related to anything in my PR.

For example,

```
TASK [bundle_validation_filter : Set fact] *************************************
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'bvf_label' is undefined. 'bvf_label' is undefined
  
    The error appears to be in '/home/runner/.ansible/pull/fv-az1028-527.atwrdzpjfxuexoqyq1q1ta0xqe.cx.internal.cloudapp.net/upstream/roles/bundle_validation_filter/tasks/generate_label.yml': line 94, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: "Set fact"
      ^ here
```

**Comment by jmazzitelli** [comment]
That error seems to have been fixed, but still getting CI test runs unable to finish.

see https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2747

**Comment by mporrato** [comment]
The issue with the bundle validation filter role has been fixed. We are currently investigating another issue in the pipeline that is causing orange tests to fail.

**Comment by mporrato** [comment]
Orange tests are now fixed. Closing.
