### ISSUE TITLE
Index fails to update due to CI timeout

### ISSUE THREAD

**Issue by rawagner** [redhat-openshift-ecosystem/community-operators-prod#2826]
Im having issues with CI timeouting https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/5303002797 . This is the 3rd time It happened in the last few days, Im also seeing other similar jobs to fail on timeout.

The operator PRs were successfully merged https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2821 https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2812 https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2803 but the new version is not released due to failing CI.

Can you please help ? 
Is there something wrong with the cluster-aas-operator bundle that could cause this ?

**Comment by dgn** [comment]
We're seeing the same thing with maistraoperator builds... Not sure if it is caused by us. It seems that some operator CSVs are pushed to the index?

**Comment by sedadas** [comment]
The same seems to be the case with the opstree redis-operator as well:
<https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/5298228155>
This one didn't even pass the traffic light check.
