### ISSUE TITLE
Remove GitLab operator from OCP 4.13

### ISSUE THREAD

**Issue by OchiengEd** [redhat-openshift-ecosystem/community-operators-prod#2988]
Older versions of the GitLab operator are showing up in OCP 4.13, specifically versions released prior to v0.19.2. This has been identified to be caused by the missing metadata `com.redhat.openshift.versions: v4.10-v4.12` in the annotations.yaml.

Could the operator be removed from the OCP 4.13 operators index at this time until GitLab can ensure the operator can operate as expected in OpenShift v4.13?

**Comment by mnielsen-gitlab** [comment]
cc @tomasbakk given involvement in recently merged PRs.

**Comment by mnielsen-gitlab** [comment]
Commenting to keep this open.

**Comment by mnielsen-gitlab** [comment]
@tomasbakk - I see you reacted to my comment above but we're getting [reports](https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/issues/1270#note_1544138922) that this is still a problem. Is there anything I can do to help push this along?

**Comment by ezopezo** [comment]
Hello, we are currently working on fix in manual release workflow. Manual re-release on v4.13 index should resolve this issue. I'll get back to this thread after is done.

**Comment by mnielsen-gitlab** [comment]
Much appreciated, thanks for the confirmation 👍

**Comment by ezopezo** [comment]
Hello, index for 4.13 has been re-released today, can you please confirm absence of the operator bundle in 4.13?

**Comment by mnielsen-gitlab** [comment]
@ezopezo - a [question](https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/issues/1314#note_1556221229) from a customer:

> Still showing with on-prem VMware OCP 4.13.11. I'm unsure whether the RH team is saying that the problem can be solved with the index alone or whether the old annotations need to be addressed (or even easier, a new superseding release targeting 4.13) along with an index rebuild.

**Comment by ezopezo** [comment]
It seems that manual release did not make a trick. Currently we are in the process of fixing subsequent issues resulted from bug in manual release and then we will proceed with investigating this. Thanks for patience!

**Comment by mnielsen-gitlab** [comment]
Bump 👍

**Comment by mporrato** [comment]
@mnielsen-gitlab you will need to submit a PR to add the `com.redhat.openshift.versions` annotation to the bundles.

**Comment by mnielsen-gitlab** [comment]
They're present now ([example from latest release](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/gitlab-operator-kubernetes/0.24.1/metadata/annotations.yaml), and part of our release scripting as far back as [0.19.1](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/gitlab-operator-kubernetes/0.19.0/metadata/annotations.yaml). 

So to clarify, do you mean we need to submit a PR to update all of the versions that _don't_ set the annotation? It was my impression that we couldn't release or update older versions.

**Comment by mporrato** [comment]
> So to clarify, do you mean we need to submit a PR to update all of the versions that _don't_ set the annotation? It was my impression that we couldn't release or update older versions.

Yes, that's what I mean. Usually updates to existing bundles should be accepted only for changes that affect the presentation of the operator on the operatorhub portal, but if you want to disallow the installation of those bundles on newer ocp versions, you have no other option as the release pipeline always tries to align what's in the indices to what is declared in the git repo: even if we went ahead and manually removed those bundles from the indices, they would be added back whenever you will release your next bundle.

**Comment by mnielsen-gitlab** [comment]
Thank you for clarifying that, we'll work on getting a PR ready.

**Comment by pursultani** [comment]
A draft solution is submitted in #3503. I expect it to break some of the checks.
