### ISSUE TITLE
4.8 community-operators missing a bundle

### ISSUE THREAD

**Issue by madorn** [redhat-openshift-ecosystem/community-operators-prod#312]
Recently merged dell-csi-operator is missing from `registry.redhat.io/redhat/community-operator-index:v4.8`

**Comment by mvalarh** [comment]
I can confirm that it is missing in v4.8. Looking it to it now

**Comment by mvalarh** [comment]
It should be fixed now. Please reopen when needed

**Comment by J0zi** [comment]
@madorn, the operator is there 
![image](https://user-images.githubusercontent.com/51358681/136750439-49029e59-130a-434e-85eb-c3ccb04e8ad8.png)
