### ISSUE TITLE
Links to instructions for PR approvals are broken

### ISSUE THREAD

**Issue by maskarb** [redhat-openshift-ecosystem/community-operators-prod#3197]
Clicking a link to instructions for approving a PR are broken:
```
https://%24%7Bopp_this_repo_org%7D.github.io/$%7BOPP_THIS_REPO_NAME%7D/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator
```

**Comment by sthaha** [comment]
Seem to me like it is referring to https://redhat-openshift-ecosystem.github.io/community-operators-prod/

**Comment by maskarb** [comment]
Here is an example where a link is broken:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3224#issuecomment-1710848076

If that link is supposed to take us to https://redhat-openshift-ecosystem.github.io/community-operators-prod/, that's fine, but I cannot find anywhere on that site how to approve a PR.
