### ISSUE TITLE
PR is all green and submitted by authorized user, but not merged

### ISSUE THREAD

**Issue by jmazzitelli** [redhat-openshift-ecosystem/community-operators-prod#3262]
I have a PR that shows all tests passing (everything is green), contains a signed commit, and was submitted by [an authorized user](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/kiali/ci.yaml). However, for some reason the PR was not automatically merged like it has always done in the past.

Is there a problem with auto-merge?

This PR is the one that is not merging: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3254

**Comment by mporrato** [comment]
This is the expected behaviour when an update to an existing bundle is non-trivial.

**Comment by mporrato** [comment]
This is the expected behaviour when an update to an existing bundle is non-trivial.

**Comment by jmazzitelli** [comment]
no a problem with auto-merge.. apparently that PR was changing things that forbid it from being auto-merged.
