### ISSUE TITLE
community operators are not being published 

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#3380]
I created https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3376 yesterday,
and it passed all the tests and was merged.

But AFAICS cert-manager 1.13.1 is not available in the OperatorHub UI of Openshift 4.13.

It looks like the CI pipeline that publishes the community operators catalog may be broken:
 * https://github.com/redhat-openshift-ecosystem/community-operators-prod/actions/runs/6401752958/job/17381577923

...since https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3362 got merged.

<img width="450" alt="image" src="https://github.com/redhat-openshift-ecosystem/community-operators-prod/assets/978965/16329e3b-fd3d-4f36-98d8-1b5ea3dae6f5">

/kind bug

**Comment by vrutkovs** [comment]
@mvalarh could you have a look?

**Comment by dmage** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3374 is an attempt to fix it.

**Comment by wallrj** [comment]
Thanks @dmage The package is now appearing on OpenShift 4.13

<img width="960" alt="image" src="https://github.com/redhat-openshift-ecosystem/community-operators-prod/assets/978965/6bdb680a-1401-4188-a0cc-b925f8320abc">
