### ISSUE TITLE
`opm alpha bundle generate`  does not target manifests directories

### ISSUE THREAD

**Issue by secondsun** [redhat-openshift-ecosystem/community-operators-prod#352]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/ef73c7f08d0ab33ca0a10013de15a8cbf7e238a2/ci/prow/openshift-deploy-core.sh#L195

Shouldn't this line target the manifests subdirectory of the operator bundle?  The example formats given in most of the operator-registry documentation and the opm alpha bundle generate help files would seem to indicate this.

`  -d, --directory string     The directory where bundle manifests for a specific version are located.`

@mvalarh This may be the issue with my PR.

**Comment by stujb** [comment]
Would this issue have caused the grafana-operator to have disappeared from the community-operators ? Building an OKD4.8 cluster using " - image: registry.access.redhat.com/redhat/community-operator-index:v4.9" and the grafana operator no longer appears.
