### ISSUE TITLE
Links to instructions for PR approval are still broken

### ISSUE THREAD

**Issue by maskarb** [redhat-openshift-ecosystem/community-operators-prod#3695]
The link to instructions to approve a PR are still broken:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3694#issuecomment-1843048269

The link takes you to
```
https://${opp_this_repo_org}.github.io/$%7BOPP_THIS_REPO_NAME%7D/self-merge-updates/#how-can-i-approve-a-pr-against-my-operator
```

**Comment by maskarb** [comment]
Any chance these broken links can be fixed?

**Comment by Allda** [comment]
The GitHub action that produced these comments is removed and replaced by a new solution. Do you still see any broken links?

**Comment by maskarb** [comment]
This can be closed since the links I had been referring to no long appear to be a thing this repo's actions send to the PRs.
