### ISSUE TITLE
Broken links to "categories" in documentation

### ISSUE THREAD

**Issue by alanconway** [redhat-openshift-ecosystem/community-operators-prod#3771]
For example: 

docs/packaging-required-fields.md:53:For the best user experience, choose from the [categories](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/categories.json).

I cant find categories.json anywhere in the repo.

**Comment by alanconway** [comment]
Here's a more complete list from doc/*

packaging-operator.md:21:An Operator's CSV must contain the fields mentioned [here](./packaging-required-fields.md#packaging-required-fields-for-operatorhub) for it to be displayed properly within the various platforms. If your operator needs a new category, follow the instructions about [categories](./packaging-required-fields.md#categories).
packaging-required-fields.md:17:    categories: A comma separated list of categories from the values below. If not set, this will be set to "Other" in the UI
packaging-required-fields.md:53:For the best user experience, choose from the [categories](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/categories.json).
packaging-required-fields.md:55:If none of these categories fit your operator, please open a separate PR against [categories.json](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/categories.json). Once merged, you can open a PR with your operator assigned to your new category.
packaging-required-fields.md:67:    categories: "OpenShift Optional"
pull_request_template.md:30:* [ ] Valid [category name](./packaging-operator.md#categories)<sup>1</sup>
pull_request_template.md:40:<sup>1</sup> If you feel your Operator does not fit any of the pre-defined categories, file an issue against this repo and explain your need

**Comment by Allda** [comment]
Thanks for reporting the issue with doc reference. The issue has been fixed and reference is valid again.
