### ISSUE TITLE
Error in community hosted pipeline

### ISSUE THREAD

**Issue by lachlan-ibm** [redhat-openshift-ecosystem/community-operators-prod#3783]
I am having a problem running the community hosted pipeline for PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3772

The pipeline seems to be failing due to it being unable to find a reviewer. The user in question https://github.com/scottexton still exists and their profile is active.

I am unsure what I can do to resolve this issue

Thanks

**Comment by andreasgerstmayr** [comment]
Looks like I ran into the same issue: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3866

The logs of the `get-ci-reviewer` tasks show that the an user is not found, but this user exists in GitHub and also approved the PR.

**Comment by Allda** [comment]
The bugfix has been already released and the issue with non-existent users is fixed.
