### ISSUE TITLE
File Based Catalog

### ISSUE THREAD

**Issue by Allda** [redhat-openshift-ecosystem/community-operators-prod#3890]
The community operator pipeline is based on a model where community members and operator owners submit their new operators and the pipeline itself takes care of building, testing, and distributing a bundle to all supported OCP catalogs. This model allows a quick submission of new versions to the catalog on one hand but does not allow any further modification of the catalog and upgrade paths on the other hand.

The team that is now responsible for the community pipeline is actively working on support for [FBC (File-based catalog)](https://olm.operatorframework.io/docs/reference/file-based-catalogs/) that allows more complex use-cases for a catalog like direct modification of the upgrade paths, addition of multiple bundles, deletion of existing bundles and many more.

This initiative started already in Q4 and we are finalizing the design of the new pipeline in Q1 and continue with development later on.

**Comment by astoycos** [comment]
/reopen

Is this still being worked on? The bpfd-operator is still listed in `community-operators-prod` even though it should not

We are however about to cut a release with the [project's](bpfman.io) new name `bpfman` so I'll be pushing manifests for that soon
