### ISSUE TITLE
Fixing having bundles of different names

### ISSUE THREAD

**Issue by chipzoller** [redhat-openshift-ecosystem/community-operators-prod#4097]
I have a PR open (#4087) in which the pipeline is failing because of bundles having different names. This appears to be caused by a previous version of an operator which uses a different bundle name from all other operators. Seeing as how one can neither modify an old operator nor remove a specific version, how do I proceed? I'll note that this check was not present for my previous PR (#3662) and the current PR is virtually identical to that previous one including the bundle name. I appear to be stuck. What's the solution here?

**Comment by chipzoller** [comment]
Ping

**Comment by jsenko** [comment]
I have the same issue here https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4174 . Can anyone take a look please?
