### ISSUE TITLE
community-hosted-pipeline tests should not ignore missing bundle

### ISSUE THREAD

**Issue by clobrano** [redhat-openshift-ecosystem/community-operators-prod#4276]
If the submitted operator bundle has the wrong structure (e.g. the `bundle` folder inside `operator-name/x.y.z/`, like we did by mistake in #4199) the tests ignore the lack of bundle or catalog and terminates with success

```
[set-github-pr-title : set-github-status] + TITLE=
[set-github-pr-title : set-github-status] + echo 'Setting the PR title'
[set-github-pr-title : set-github-status] Setting the PR title
[set-github-pr-title : set-github-status] No bundles nor catalogs have been added/updated
[set-github-pr-title : set-github-status] + [[ '' != '' ]]
[set-github-pr-title : set-github-status] + [[ '' != '' ]]
[set-github-pr-title : set-github-status] + [[ '' != '' ]]
[set-github-pr-title : set-github-status] + echo 'No bundles nor catalogs have been added/updated'
[set-github-pr-title : set-github-status] + exit 0
```

full log: https://gist.github.com/rh-operator-bundle-bot/6e5f4598ee34371a84a11709b7aa0b58

I think not finding the bundle should result in an error instead.

**Comment by mporrato** [comment]
The behaviour of skipping the rest of the ci pipeline if there is no new bundle in the PR is by design. However the PR should not be automatically merged in this situation.

Thanks for reporting the issue: we will address it.
