### ISSUE TITLE
Grafana operator not available in Openshift 4.16

### ISSUE THREAD

**Issue by bose-abhishek** [redhat-openshift-ecosystem/community-operators-prod#4595]
Grafana operator is not available in Openshift 4.16 (pre-GA version) . 
It seems the [annotations.yaml](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/grafana-operator/5.8.0/metadata/annotations.yaml#L14) file restricts the OCP version: `com.redhat.openshift.versions: "v4.11-v4.15"`

Please let us know when the Grafana operator will be available in OCP-4.16.
Is there any plans for a major change in the operator for OCP-4.16 or just the version needs to be updated in the file.

cc @theSuess as he has last committed in the file.

Thanks.

**Comment by theSuess** [comment]
Hey, AFAIK there is nothing preventing the operator to work on 4.16. We're going to publish a new catalog release in the coming days and will bump that annotation alongside - thanks for calling this out!

**Comment by bose-abhishek** [comment]
Yes, the issue is now resolved and I can install the grafana operator in OCP 4.16. 
Thank you for promptly looking into the issue.
