### ISSUE TITLE
Update Metadata Annotations for the Trident Operator

### ISSUE THREAD

**Issue by sabman3** [redhat-openshift-ecosystem/community-operators-prod#4658]
The metadata annotation for the Trident Operator (https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/trident-operator/24.2.0/metadata/annotations.yaml) shows support only up to OpenShift 4.14. But according to NetApp, OpenShift 4.15 is supported. My guess is a typo in the annotation.  Please let me know if this is wrong place to raise this issue too.

**Comment by benruland** [comment]
I have created a PR for that: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4721

However, I am not sure, that this was the intended way...

**Comment by haripate** [comment]
@benruland It is not allowed to modify the existing operator bundle.

**Comment by reederc42** [comment]
Trident 24.06.0 has been released, and I've removed the version annotations, so you should be able to install it on any version of openshift. Our support policies are the same, i.e. you should install it on supported versions of k8s/openshift (https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#critical-information-about-astra-trident), but there won't be a technical restriction.

@benruland @sabman3

**Comment by benruland** [comment]
Thanks! I would consider this issue as Closed then. 

PR is https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4771
