### ISSUE TITLE
Need help with merging PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5135

### ISSUE THREAD

**Issue by rajendraindukuri** [redhat-openshift-ecosystem/community-operators-prod#5171]
Hi,

We raised a  PR to deprecate dell-csi-operator and we are seeing some failures in the PR checks.

Details of the PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5135

Need help in bringing this PR to closure.

**Note:** We are able to remove it from the Redhat catalog and we don't see it when we search for it

Thanks
Rajendra

**Comment by rajendraindukuri** [comment]
Can anyone please help take a look into this ? Thanks.

**Comment by Allda** [comment]
@rajendraindukuri Operator removal action is only allowed for operators that use the FBC mode. If you want to deprecate your operator please follow the FBC onboarding as announced here: https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/5031

Once you have your operator onboarded you can remove selected bundles and the pipeline will pass with no validation errors. If you need any guidance with onboarding please let me know. I can assist you with the process.
