### ISSUE TITLE
Grafana operator not available in Openshift 4.17 (pre-GA)

### ISSUE THREAD

**Issue by bose-abhishek** [redhat-openshift-ecosystem/community-operators-prod#5198]
Grafana operator is currently not available in OCP-v4.17 (pre-GA version).
It seems the [annotations.yaml](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/grafana-operator/5.9.2/metadata/annotations.yaml) file restricts the OCP version: `com.redhat.openshift.versions: "v4.11-v4.16"`

Please let us know when the Grafana operator will be updated to include in OCP-4.17.

This issue is similar to https://github.com/redhat-openshift-ecosystem/community-operators-prod/issues/4595

Is there any reason to limit the OCP version in the annotations.yaml file? 
If there are no restrictions, can we have current version+1 included in the file to support pre-GA testing.

Thanks.

cc @theSuess

**Comment by theSuess** [comment]
resolved in #5369
