### ISSUE TITLE
PR is not getting automatically merged even when the checks are passing

### ISSUE THREAD

**Issue by rajendraindukuri** [redhat-openshift-ecosystem/community-operators-prod#5312]
Hi,

As part of the certification process, we raised a PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5290

Even though the pipeline checks are passing, we are not able to close this PR.

Can you please help with closing this PR?

Thanks
Rajendra

**Comment by mporrato** [comment]
Done
