### ISSUE TITLE
Projects shipped with invalid examples

### ISSUE THREAD

**Issue by camilamacedo86** [redhat-openshift-ecosystem/community-operators-prod#630]
Note that a new check to help us ensure the CSV definition by ensuring that the alm-example JSON is parsable, see:
- https://github.com/operator-framework/operator-sdk/pull/5495

After the next SDK release (1.17.0) we can start to check it in the ci/pipeline and does not allow this scenario. However, the idea of this task is to let its authors know that their CSV contains invalid examples and ask for them to fix that. 

The following packages and distributions are with invalid examples

**infinispan**: 

- Distribution: infinispan-operator.v2.1.3

`Error: Value invalid character at 1260 [ { "apiVersion": "infinispan.org/v1", "kind": "Infinispan", "metadata": { "name": "example-infinispan" }, "spec": { "replicas": 1 } }, { "apiVersion": "infinispan.org/v2alpha1", "kind": "Backup", "metadata": { "name": "example-backup" }, "spec": { "cluster": "example-infinispan", "container": { "cpu": "1000m", "extraJvmOpts": "-Djava.property=me", "memory": "1Gi" }, "path": "asdasd" } }, { "apiVersion": "infinispan.org/v2alpha1", "kind": "Cache", "metadata": { "name": "example-cache" }, "spec": { "adminAuth": { "secretName": "basic-auth" }, "clusterName": "example-infinispan", "name": "mycache" } }, { "apiVersion": "infinispan.org/v2alpha1", "kind": "Restore", "metadata": { "name": "example-restore" }, "spec": { "cluster": "example-infinispan", "container": { "cpu": "1000m", "extraJvmOpts": "-Djava.property=me", "memory": "1Gi" }, "path": "asdasd" } }, { "apiVersion": "infinispan.org/v2alpha1", "kind": "Batch", "metadata": { "name": "example-batch", }<--(see the invalid character): invalid example`

**pulp-operator**

- pulp-operator.v0.4.0

`Error: Value invalid character at 359 [ { "apiVersion": "pulp.pulpproject.org/v1beta1", "kind": "Pulp", "metadata": { "name": "example-pulp" }, "spec": { "storage_type": "File", "file_storage_size": "50Gi", "file_storage_access_mode": "ReadWriteMany", "image": "quay.io/pulp/pulp:3.16.0", "image_web": "quay.io/pulp/pulp-web:3.16.0", }<--(see the invalid character): invalid example`

- pulp-operator.v0.3.0

`Error: Value invalid character at 322 [ { "apiVersion": "pulp.pulpproject.org/v1beta1", "kind": "Pulp", "metadata": { "name": "example-pulp", "namespace": "example-pulp" }, "spec": { "tag": "0.3.0", "storage_type": "File", "file_storage_size": "50Gi", "file_storage_access_mode": "ReadWriteMany", }<--(see the invalid character): invalid example
`

- tf-operator

- tf-operator.latest

`Error: Value invalid character at 1464 [ { "apiVersion": "tf.tungsten.io/v1alpha1", "kind": "Manager", "metadata": { "name": "cluster1", "namespace": "tf" }, "spec": { "commonConfiguration": { "authParameters": { "authMode": "noauth" }, "hostNetwork": true, "replicas": 3, "useKubeadmConfig": true }, "services": { "analytics": { "metadata": { "labels": { "tf_cluster": "cluster1" }, "name": "analytics1" }, "spec": { "commonConfiguration": { "nodeSelector": { "node-role.kubernetes.io/master": "" } }, "serviceConfiguration": { "containers": [ { "image": "docker.io/tungstenfabric/contrail-analytics-api:latest", "name": "analyticsapi" }, { "image": "docker.io/tungstenfabric/contrail-analytics-collector:latest", "name": "collector" }, { "image": "docker.io/tungstenfabric/contrail-nodemgr:latest", "name": "nodemanager" }, { "image": "docker.io/tungstenfabric/contrail-provisioner:latest", "name": "provisioner" } ], }<--(see the invalid character): invalid example`

**Comment by camilamacedo86** [comment]
@J0zi @mvalarh could you help us by pinging its authors here?

**Comment by mvalarh** [comment]
Fixed in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/783
