### ISSUE TITLE
Update the readme to clarifies to the users

### ISSUE THREAD

**Issue by camilamacedo86** [redhat-openshift-ecosystem/community-operators-prod#782]
We need to add into the readme:
- That the image built from the projects merged here is `registry.redhat.io/redhat/community-operator-index:v<tag>`
- Clarifies that this repository is used to create the image and this image is used to distribute solutions on OCP/OKD by default
- Clarifies that the solutions merged here ought to work in the OKD and OCP 
- Clarifies that OCP catalog is created by default using multi-sources and link the doc: https://docs.openshift.com/container-platform/4.6/operators/understanding/olm-rh-catalogs.html#olm-rh-catalogs_olm-rh-catalogs

**Comment by J0zi** [comment]
for now, it is here https://redhat-openshift-ecosystem.github.io/community-operators-prod/operator-release-process/#operator-is-published

**Comment by camilamacedo86** [comment]
Hi @J0zi, 

the above info is essential for users and IMO that would need to be in the readme. 
also, see that the link provided does not cover all.
