### ISSUE TITLE
Example to prune catalogs with FBC

### ISSUE THREAD

**Issue by camilamacedo86** [redhat-openshift-ecosystem/community-operators-prod#793]
From @madhukirans in (https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/512#discussioncomment-2152837):

Would it be possible to get an example workflow of pruning the upstream catalog index of all for specified operators? Do all i have to do is replace the 'opm index prune' command with 'rm' commands to get this working agian? The current sqlite workflow i have is:

  ```
  echo "- pruning catalog index"
    MIRROR_CATALOG_LINE="./opm index prune -f ${OCP_OPERATORS_UPSTREAM_CATALOG} -p `echo $OCP_OPERATORS_KEEP` -t ${BOOTSTRAP_REGISTRY}/catalog-x86-disconnected:latest"

    echo $MIRROR_CATALOG_LINE
    eval $MIRROR_CATALOG_LINE
    
    echo "- pushing pruned catalog index locally"
    MIRROR_CATALOG_PUSH_LINE="podman push ${BOOTSTRAP_REGISTRY}/catalog-x86-disconnected:latest"
    echo $MIRROR_CATALOG_PUSH_LINE
    eval $MIRROR_CATALOG_PUSH_LINE
    
    echo "- sync'ing catalog locally"
    rm -rf manifests-catalog-x86-disconnected
    MIRROR_CATALOG_IMAGES="oc adm catalog mirror ${BOOTSTRAP_REGISTRY}/catalog-x86-disconnected:latest ${BOOTSTRAP_REGISTRY} --to-manifests=manifests-catalog-x86-disconnected --index-filter-by-os='linux/amd64' --manifests-only -a ${PULL_SECRET_JSON_FILE}"
    echo $MIRROR_CATALOG_IMAGES
    eval $MIRROR_CATALOG_IMAGES
    
    cd manifests-catalog-x86-disconnected
    cat mapping.txt |grep -v -e "^${BOOTSTRAP_REGISTRY}" > mappings.txt
    MIRROR_IMAGES_LINE="oc image mirror --skip-multiple-scopes=true -a ${PULL_SECRET_JSON_FILE} --filter-by-os='linux/amd64' -f mappings.txt"
    echo $MIRROR_IMAGES_LINE
    eval $MIRROR_IMAGES_LINE
```
A working example would be super helpful in helping folks with 'disconnected' requirements

**Comment by camilamacedo86** [comment]
Following an example:

**To prune a file-based catalog of all packages except desired package/s, use the following steps:** 

1) Create the dir:
```sh
mkdir -p pruned-catalog/configs
```

2) Render index for the package: 
```sh
opm render <index-image> | jq 'select( .package == <package-name> or .name == <package-name>)' > pruned-catalog/configs/index.json 
```

For example:

```sh
opm render quay.io/operatorhubio/catalog:tmp_latest_fbc | jq 'select( .package == "lib-bucket-provisioner" or .name == "lib-bucket-provisioner")'> pruned-catalog/configs/index.json
```

3) Generate the index image 

```
opm alpha generate dockerfile pruned-catalog/configs && cd pruned-catalog/
```

4) Build and publish the image:

```
podman build -t <pruned-catalog-image> -f pruned-catalog.Dockerfile . podman push <pruned-catalog-image>
```
 
**Caveat:** If an FBC catalog is using an [extension schema](https://github.com/operator-framework/enhancements/blob/master/enhancements/declarative-index-config.md#extension-formats) AND the extension schema has a package field AND the extension schema has a field that references another non-fbc file, we won't bring that file along. However, the extension schema hasn’t been documented yet. If extension schemas get adopted by operator authors in the future the imperative pruning workflow needs to be switched for (ideally) a declarative way of pruning the catalog.

**Comment by camilamacedo86** [comment]
Following an example:

**To prune a file-based catalog of all packages except desired package/s, use the following steps:** 

1) Create the dir:
```sh
mkdir -p pruned-catalog/configs
```

2) Render index for the package: 
```sh
opm render <index-image> | jq 'select( .package == <package-name> or .name == <package-name>)' > pruned-catalog/configs/index.json 
```

For example:

```sh
opm render quay.io/operatorhubio/catalog:tmp_latest_fbc | jq 'select( .package == "lib-bucket-provisioner" or .name == "lib-bucket-provisioner")'> pruned-catalog/configs/index.json
```

3) Generate the index image 

```
opm alpha generate dockerfile pruned-catalog/configs && cd pruned-catalog/
```

4) Build and publish the image:

```
podman build -t <pruned-catalog-image> -f pruned-catalog.Dockerfile . podman push <pruned-catalog-image>
```

**Comment by camilamacedo86** [comment]
I am closing this one as sorted out. However, please let us know if you think that needs to be re-opened.

**Comment by zfrhv** [comment]
> 4. Build and publish the image:
> ```
> podman build -t <pruned-catalog-image> -f pruned-catalog.Dockerfile . podman push <pruned-catalog-image>
> ```
i guess it should be: (?)
```
podman build -t <pruned-catalog-image> -f configs.Dockerfile . && podman push <pruned-catalog-image>
```
because `pruned-catalog.Dockerfile` doesnt exists, only `configs.Dockerfile` exists, and also seems that `&&` is missing

**Comment by camilamacedo86** [comment]
H @zfrhv,

This issue is closed. if you need any help or are facing an issue could you please raise a new one with your scenario?

**Comment by zfrhv** [comment]
hello @camilamacedo86 ~

i dont have any problems, im just pretty sure that there is a typo

**Comment by AsherShoshan** [comment]
conflicting options with opm versions.  on one version "opm alpha generate" is not working, there is "opm alpha generate bundle", however rest of params are not valid.

**Comment by Ladanow** [comment]
Any idea why OpenShift is not recognizing the render option?

`[mano@bastion ~]$ opm rendre quay.io/operatorhubio/catalog:latest 
Error: unknown command "rendre" for "opm"
Run 'opm --help' for usage.
[mano@bastion ~]$ opm --help
CLI to interact with operator-registry and build indexes of operator content

Usage:
  opm [command]

Available Commands:
  help        Help about any command
  index       generate operator index container images
  registry    interact with operator-registry database
  version     Print the opm version

Flags:
  -h, --help       help for opm
      --skip-tls   skip TLS certificate verification for container image registries while pulling bundles or index

Use "opm [command] --help" for more information about a command.
[mano@bastion ~]$ oc version 
Client Version: 4.8.14
Server Version: 4.10.13
Kubernetes Version: v1.23.5+b463d71
[mano@bastion ~]$`

**Comment by orenc1** [comment]
Hi @Ladanow ,
you should use a recent `opm` tool version that includes the `render` command.
the tool binary can be acquired at: https://github.com/operator-framework/operator-registry/releases

**Comment by Ladanow** [comment]
That worked!
Thanks
