### ISSUE TITLE
Document where to get the source code for the GitHub Action: operator-framework/community-operators

### ISSUE THREAD

**Issue by wallrj** [redhat-openshift-ecosystem/community-operators-prod#795]
The documentation refers to a GitHub Action but it does not link to the source code for the action:
 * https://redhat-openshift-ecosystem.github.io/community-operators-prod/action/

https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/gh-pages/action/index.html
https://github.com/k8s-operatorhub/community-operators/blob/gh-pages/action/index.html

I eventually found it here: https://github.com/operator-framework/community-operators/tree/action/stable in a branch of the archived repository. 

I'd create a PR, but it's also not clear where the source markdown now lives. 
All I could find was https://github.com/operator-framework/community-operators/blob/master/docs/action.md in the archived repository.

/cc @mvalarh

**Comment by camilamacedo86** [comment]
Hi @wallrj, 

The docs shared I think are valid for who will contribute with the CI/pipeline. 
However, (IMO) for Operator Authors (contributors) we ought to suggest: 

Use [SDK CLI](https://github.com/operator-framework/operator-sdk) latest release to check out your bundle against it with:

```
operator-sdk bundle validate ./bundle --select-optional suite=operatorframework
```
Which is here as well: https://olm.operatorframework.io/docs/best-practices/common/

The CI/pipeline does not use the default [Scorecard](https://sdk.operatorframework.io/docs/testing-operators/scorecard/) config tests to check the operator bundles but I also would like to suggest to you check your bundle to improve the quality of your project.
