### ISSUE TITLE
Please update the spark-on-k8s operator

### ISSUE THREAD

**Issue by sousaaguilherme** [redhat-openshift-ecosystem/community-operators-prod#848]
The spark-on-k8s by GoogleCloudPlatform is very old (2019) and won't be compatible with OCP 4.9.

Can you please update it?

Best regards

**Comment by J0zi** [comment]
Please contact operator contributors/authors here https://github.com/k8s-operatorhub/community-operators.

**Comment by sousaaguilherme** [comment]
Thanks @J0zi !
