### ISSUE TITLE
build: jaeger operator 1.32 failed on main branch

### ISSUE THREAD

**Issue by frzifus** [redhat-openshift-ecosystem/community-operators-prod#941]
Jaeger release 1.32 is failed on the main branch. https://github.com/redhat-openshift-ecosystem/community-operators-prod/commit/d24d33e6fb987bed19b352faa9b07b6930983562

Before that, it successfully passed the ci. https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/933

Unfortunately, I didn't quite figure out from the [logs](https://github.com/redhat-openshift-ecosystem/community-operators-prod/runs/5543103049?check_suite_focus=true#step:5:3286) what went wrong. 

Is it simply caused by flakiness or is some action needed?

Best regards

**Comment by J0zi** [comment]
Closing since it was merged.
